### ISSUE TITLE
scylla-check-gossiper-generation hits false-positive matches

### ISSUE THREAD

**Issue by dmeetryk** [scylladb/scylla-code-samples#130]
Pattern used in the script to select "node-IP-section" (`grep -A1 "$IP"`) allows false positives if searched IP is a sub-string of another node IPs. As result the script fails.
E.g. (in our setup):
```bash
$ IP=$(hostname -i) && nodetool gossipinfo | grep -A1 "$IP"
/10.3.80.6
  generation:1583954108
#...
--
/10.3.80.69
  generation:1583957204
#...
```

We did proceed with upgrade after modification, but would it be possible to change it to something like `grep -A1 "^/${IP}$"`?

BTW, [existing PR modifying patterns in this script](https://github.com/scylladb/scylla-code-samples/pull/128)  has the same issue only in awk pattern.

**Comment by tarzanek** [comment]
@dmeetryk hello, is this still relevant in the scope of merged https://github.com/scylladb/scylla-code-samples/pull/151 ?
if not, we can close this
