### ISSUE TITLE
`gce_deploy_and_install_scylla_cluster` is out of date

### ISSUE THREAD

**Issue by fruch** [scylladb/scylla-code-samples#146]
one of our user try to follow it
https://scylladb-users.slack.com/archives/C2NLNBXLN/p1601488594085300?thread_ts=1601425345.080800&cid=C2NLNBXLN

and seems like this one is very out of data.

we might want to consider removing it (if not updating it)

**Comment by tzach** [comment]
@bentsi can you help with an up to date example?

**Comment by tzach** [comment]
BTW, we need to review this entire repo, there are probably more out of date examples here

**Comment by fruch** [comment]
> BTW, we need to review this entire repo, there are probably more out of date examples here

yeah but this one a user had question about, and it's a bit conflicting with other docs we have.

**Comment by fruch** [comment]
my vote is that we remove that if we have other recommendation, like moving this to be part of 
https://github.com/scylladb/scylla-ansible-roles

@dyasny seems to did a good job there, adding a script that would create the instances from commandline is missing there (we could have examples for both AWS and GCE, and other later on)

**Comment by tzach** [comment]
> my vote is that we remove that 

Agree. Please send a PR
