### ISSUE TITLE
Range defined in the query should be open from one side.

### ISSUE THREAD

**Issue by rtatishvili** [scylladb/scylla-code-samples#181]
Shouldn't the query contain the range open from only one side, in other words, if `>=` is the lower bound, then upper bound should be strict inequality:`<` ?

In the vastness of the token range this is an edge case, but will probably catch someday someone.

https://github.com/scylladb/scylla-code-samples/blob/737432904a7a370544e01289758d4449b101a0d4/efficient_full_table_scan_example_code/efficient_full_table_scan.go#L21

**Comment by DanielHe4rt** [comment]
Maybe this article can help you to understand a little bit better, @rtatishvili.

[Efficient Full Table scans with ScyllaDB](https://resources.scylladb.com/scylladb-best-practices/efficient-full-table-scans-with-scylladb)
