### ISSUE TITLE
Error while deploying on bare metal servers.

### ISSUE THREAD

**Issue by EmMerry** [scylladb/scylla-code-samples#24]
This might be out of the scope issue or not even an issue. I am trying to deploy the scylla on kubernetes, baremetal server. I have installed the Kubernetes 1.9 on 2 nodes (master and node). I understand that this deployment is for google cloud but can someone points that how to configure the NFS provisioning in kubernetes. I am getting the following error while creating the deployment.

`Warning  FailedMount            25s (x4 over 7m)  kubelet, node-pc  Unable to mount volumes for pod "scylla-0_default(ef01bfc8-05b4-11e8-9bc8-98e7f452d34d)": timeout expired waiting for volumes to attach/mount for pod "default"/"scylla-0". list of unattached/unmounted volumes=[scylla-data]`

**Comment by EmMerry** [comment]
@tzach @rusher81572 any idea?

**Comment by hakuch** [comment]
@EmMerry, I'm not an expert on Kubernetes by any stretch and I could be mistaken, but this appears to be a configuration issue around Kubernetes itself and not an issue with Scylla. Perhaps it would be helpful to direct your question to a Kubernetes community?

**Comment by samhain1138** [comment]
Just FYI, looks like the Helm chart is using the `kubernetes.io/gce-pd` StorageClass, which means it will only provide storage on GCP.
I'm guessing @EmMerry is running on a different cloud provider or on-prem.

**Comment by samhain1138** [comment]
Oh, and definitely not an issue with Scylla, but also not with Kubernetes.
This is 100% the Helm chart.
I'll try to fix it tomorrow.

**Comment by samhain1138** [comment]
I addressed this issue in helm/charts#8597 by removing the default StorageClass.
You can still set a custom one, but the default would use your k8s cluster's default StorageClass
Good catch, @EmMerry !

**Comment by tzach** [comment]
@EmMerry @samhain1138 can we close this issue?

**Comment by EmMerry** [comment]
Yes verified and closing this one. Thanks everyone for help. :)
