### ISSUE TITLE
GCE deploy - cleanup

### ISSUE THREAD

**Issue by duarten** [scylladb/scylla-code-samples#25]
There should be a tool to cleanup the GCE deployment.

**Comment by tomer-sandler** [comment]
there's probably a single line of gcloud cli command to delete the VMs (the disks will be deleted automatically once the VMs are deleted).

And here it is: https://cloud.google.com/sdk/gcloud/reference/compute/instances/delete

**Comment by Arqu** [comment]
Disks from the stateful sets are not automatically deleted. The simplest way for a clean test run is to just nuke the cluster. Alternatively, it's a simple 4 step process - delete the stateful set deployment, the service, the config map and the storage provider along with disks.

I'll try to create a simple script tomorrow for it.
