### ISSUE TITLE
nodetool status exit code 137 

### ISSUE THREAD

**Issue by VinceMD** [scylladb/scylla-code-samples#57]
nodetool status does not seem to work:

it hangs for a few seconds before exiting

```kubectl -n MYNAMESPACE exec scylla-1 nodetool status
command terminated with exit code 137
```

The container also dies:

```scylla-0                               1/1       Running   0          2m
scylla-1                               0/1       Running   1          1m
```

I've tried with scylla-2.0.0 and 2.1.5

**Comment by VinceMD** [comment]
Turns out the resources defined in the manifest are too low for running nodetool status. I bumped the resource requests and removed the resources limits in my environment so that I can run nodetool status

**Comment by VinceMD** [comment]
This doc specifies 

'NOTE: You should allocate a minimum of 1.5 GB of RAM per container.'
http://docs.scylladb.com/procedures/best_practices_scylla_on_docker/

**Comment by tzach** [comment]
Closing this as the limitation is documented.
@VinceMD for future reference, how much RAM did you used on each try, failed and successful?
