### ISSUE TITLE
[Kubernetes | HELM] allow Snitch selection and other options

### ISSUE THREAD

**Issue by Vince-Cercury** [scylladb/scylla-code-samples#58]
Should the entire scylla.yaml be exposed as a configmap in Kubernetes?

The important requirement for me is to be able to select the Snitch. The docker image does not seem to offer the option.  

See related issue https://github.com/scylladb/scylla/issues/2048

**Comment by gnumoreno** [comment]
Absolutely should. It is on my plans to do it and since now I have a request from you I will prioritize it!

**Comment by Arqu** [comment]
+1 
Currently, the deployment on Kubernetes can produce some issues because by default the snitch hands out node IPs instead of pod IPs thus breaking stuff if not super careful and handling all the exceptions.
