### ISSUE TITLE
[HELM] namespace is hardcoded to default

### ISSUE THREAD

**Issue by Vince-Cercury** [scylladb/scylla-code-samples#59]
# What do I expect to see?
helm install --namespace mynamespace kubernetes-scylla

I expected to see a fully working Scylla cluster in `mynamespace`

# What did I see instead?
The Scylla nodes didn't start successfully. The seed node couldn't be contacted

In statefulset.yaml, this line needs to be changed:

{{ template "scylladb.fullname" . }}-0.{{ template "scylladb.fullname" . }}.default.svc.cluster.local

and retrieve the namespace instead of using `default`

**Comment by gnumoreno** [comment]
Hey, @VinceMD nice catch! 

I will definitely change that. Thanks for your feedback.
