### ISSUE TITLE
[HELM] more than 1 seed in statefulset

### ISSUE THREAD

**Issue by Vince-Cercury** [scylladb/scylla-code-samples#60]
I assume Scylla should run with more than one seed in production. Probably 2 minimum or 3 if running across 3 zones.

I tried to alter the statefulset as follow:

        args:
          - --seeds 
          - {{ template "scylladb.fullname" . }}-0.{{ template "scylladb.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local,{{ template "scylladb.fullname" . }}-1.{{ template "scylladb.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local,{{ template "scylladb.fullname" . }}-2.{{ template "scylladb.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local

Which is what I would do for Cassandra.
However none of the nodes will start as they refuse to unless all seeds are ready. Basically they are all waiting for each other to be ready:

`ERROR 2018-07-01 23:38:03,621 [shard 0] init - Bad configuration: invalid value in 'seeds': 'scylla-scylladb-1.scylla-scylladb.vince-scylladb7.svc.cluster.local': std::system_error (error C-Ares:4, Not found)`

`ERROR 2018-07-01 23:38:43,300 [shard 0] init - Bad configuration: invalid value in 'seeds': 'scylla-scylladb-2.scylla-scylladb.vince-scylladb7.svc.cluster.local': std::system_error (error C-Ares:4, Not found)`

       
How do we specify more than one seed?

**Comment by samhain1138** [comment]
@VinceMD you set the name incorrectly, I believe.
Try:
`{{ template "scylladb.fullname" . }}-0.{{ .Release.Namespace }}.svc.cluster.local,{{ template "scylladb.fullname" . }}-1.{{ .Release.Namespace }}.svc.cluster.local,{{ template "scylladb.fullname" . }}-2.{{ .Release.Namespace }}.svc.cluster.local`

**Comment by mamoit** [comment]
I am running into the same problem.
As the statefulset starts up, the `scylla-0` pod is constantly failing because it can't find `scylla-{1..2}`.
Scylla should be able to handle seeds that are not available.
Running with just one seed works perfectly fine.
