### ISSUE TITLE
[question] Kubernetes - ScyllaDB

### ISSUE THREAD

**Issue by yanniszark** [scylladb/scylla-code-samples#66]
I was taking a look at how ScyllaDB handled integration with Kubernetes and I came upon this solution. While it is very elegant and utilizes Kubernetes' built-in primitives, I have a few questions, coming from a Cassandra background:

1) How do you handle Node / Disk failure ? Cassandra requires that you supply the IP address of the dead instance and I imagine that Scylla requires that too. 
2) Is there any mechanism for backup/restore/repair of the cluster without having to visit each node separately ?
3) What are other limitations you have encountered with this solution that could be tackled by developing a Kubernetes operator ? Do you find that it needs manual intervention often ?

**Comment by tzach** [comment]
@hakuch can you help?

BTW, a better place for such a question will be Scylla user list
https://groups.google.com/d/forum/scylladb-users

**Comment by hakuch** [comment]
As I've written in the blog post, a production deployment of Scylla with Kubernetes will need to address many of the issues you're describing and this is beyond the scope of this code sample and introduction.

I think these are excellent conversation topics for a discussion on the users mailing list (as Tzach has already referenced).
