### ISSUE TITLE
Spark Structured Streaming

### ISSUE THREAD

**Issue by snowch** [scylladb/scylla-code-samples#67]
It would be great to see code examples for ScylladbDB with Spark Structured Streaming.  There is an [example project](https://github.com/polomarcus/Spark-Structured-Streaming-Examples) that shows how to do this with Spark 2.2.x.  However, note that this [doesn't work](https://github.com/polomarcus/Spark-Structured-Streaming-Examples/pull/13) with the latest release (Spark 2.3.1)

**Comment by tzach** [comment]
Hi @snowch we are working on such an example, expect updates in teh next 1-2 weeks or so

**Comment by snowch** [comment]
Awesome @tzach!

**Comment by snowch** [comment]
Hey @tzach - how's the example coming along?  :)

**Comment by tzach** [comment]
There is an open PR by @iravid
https://github.com/scylladb/scylla-code-samples/pull/68

You are wellcome to review and comment.

**Comment by snowch** [comment]
I'll take a look and share with the other community - thanks!
