### ISSUE TITLE
Move to TWCS example in MMS

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla-code-samples#80]
One of the examples in the MMS example use DTCS
https://github.com/scylladb/scylla-code-samples/blob/master/mms/scylla/mutant-data.txt#L31

Examples need to be updated to TWCS

**Comment by guy9** [comment]
Done, see here:
https://university.scylladb.com/courses/the-mutant-monitoring-system-training-course/lessons/building-the-tracking-system/
@tzach please review and close

**Comment by tzach** [comment]
@guy9 did you test the example works end to end with this change?

**Comment by guy9** [comment]
@tzach  yes
