### ISSUE TITLE
MMS: use the standard monitoring stack

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla-code-samples#82]
MMS include an out of date example of the monitoring stack
https://github.com/scylladb/scylla-code-samples/tree/master/mms/monitoring
Instead, we should use the latest project, maybe as git sub module

**Comment by tzach** [comment]
@amnonh FYI

**Comment by tzach** [comment]
To connect the standard networking stack to MMS instance one should use
```
./start-all.sh -v 3.0 -D "--network mms_web"
```

**Comment by guy9** [comment]
@tzach please close, fixed here:
https://university.scylladb.com/courses/the-mutant-monitoring-system-training-course/lessons/monitoring/
